--------------------------------------------------------
--  파일이 생성됨 - 금요일-5월-27-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMINHASH
--------------------------------------------------------

  CREATE TABLE "ADMINHASH" 
   (	"HASHNAME" VARCHAR2(1000 BYTE), 
	"HASHLIKECOUNT" NUMBER DEFAULT 0, 
	"HASHCONTENTCOUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADMINTABLE
--------------------------------------------------------

  CREATE TABLE "ADMINTABLE" 
   (	"ADMINNUM" NUMBER(3,0), 
	"CONNUM" NUMBER(3,0), 
	"EMAIL" VARCHAR2(25 BYTE), 
	"RENUM" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMENTTABLE
--------------------------------------------------------

  CREATE TABLE "COMMENTTABLE" 
   (	"COMNUM" NUMBER(3,0), 
	"COMNICK" VARCHAR2(20 BYTE), 
	"COMCONTENT" VARCHAR2(1000 BYTE), 
	"COMCREATEDDATE" DATE, 
	"COMMODIFIEDDATE" DATE, 
	"COMREPORTCOUNT" NUMBER(3,0), 
	"COMBLIND" NVARCHAR2(20), 
	"CONNUM" NUMBER(3,0), 
	"EMAIL" VARCHAR2(25 BYTE), 
	"COMIP" VARCHAR2(100 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTENTS
--------------------------------------------------------

  CREATE TABLE "CONTENTS" 
   (	"CONNUM" NUMBER(3,0), 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"CONHASH" VARCHAR2(1000 BYTE), 
	"CONCREATEDDATE" DATE, 
	"CONMODIFIEDDATE" DATE, 
	"CONIP" VARCHAR2(15 BYTE), 
	"CONREPORTCOUNT" NUMBER(3,0), 
	"CONBLIND" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(25 BYTE), 
	"CONNICKNAME" VARCHAR2(100 BYTE), 
	"CONLIKE" NUMBER(3,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HASHTAG
--------------------------------------------------------

  CREATE TABLE "HASHTAG" 
   (	"TAGNAME" VARCHAR2(1000 BYTE), 
	"TAGALLCOUNT" NUMBER(3,0), 
	"TAGCONCOUNT" NUMBER(3,0), 
	"TAGINTERCOUNT" NUMBER(3,0), 
	"TAGCLASS" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "NOTICE" 
   (	"CONNUM" NUMBER(3,0), 
	"EMAIL" VARCHAR2(25 BYTE), 
	"RENUM" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PHOTO
--------------------------------------------------------

  CREATE TABLE "PHOTO" 
   (	"PHOTONUM" NUMBER(3,0), 
	"PHOTONAME" VARCHAR2(100 BYTE), 
	"REALPATH" VARCHAR2(500 BYTE), 
	"PHOTOSIZE" VARCHAR2(100 BYTE), 
	"CONNUM" NUMBER(3,0), 
	"EMAIL" VARCHAR2(25 BYTE), 
	"SERVERPATH" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPORT
--------------------------------------------------------

  CREATE TABLE "REPORT" 
   (	"RENUM" NUMBER(3,0), 
	"REDISTINCTION" VARCHAR2(20 BYTE), 
	"CONNUM" NUMBER(3,0), 
	"EMAIL" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STATS
--------------------------------------------------------

  CREATE TABLE "STATS" 
   (	"STATDATE" NUMBER(3,0), 
	"VISITCOUNT" NUMBER(3,0), 
	"CONTENTCOUNT" NUMBER(3,0), 
	"COMMENTCOUNT" NUMBER(3,0), 
	"REPORTCOUNT" NUMBER(3,0), 
	"LIKECOUNT" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERTABLE
--------------------------------------------------------

  CREATE TABLE "USERTABLE" 
   (	"EMAIL" VARCHAR2(25 BYTE), 
	"NICKNAME" VARCHAR2(20 BYTE), 
	"PASSWD" VARCHAR2(20 BYTE), 
	"HASH" VARCHAR2(1000 BYTE), 
	"AGE" NUMBER(2,0), 
	"CREATEDDATE" DATE, 
	"MODIFIEDDATE" DATE, 
	"DISTINCTION" NUMBER(1,0) DEFAULT 0, 
	"REPORTCOUNT" NUMBER(3,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table WITHDRAWAL
--------------------------------------------------------

  CREATE TABLE "WITHDRAWAL" 
   (	"DREWALNUM" NUMBER(3,0), 
	"DRAWALEMAIL" VARCHAR2(25 BYTE), 
	"DRAWALCAUSE" VARCHAR2(1000 BYTE), 
	"DRAWALDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ADMINHASH
SET DEFINE OFF;
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#사랑',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#뉴스',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#유머',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#여행',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#영화',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#다이어트',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#커피',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#친구',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#악세서리',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#생활용품',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#인터넷',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#앱',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#IT',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#성형',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#데일리',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#가족',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#동물',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#예술',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#패션',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#돈',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#운동',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#음악',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#카드',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#TV',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#결혼',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#심리학',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#요리',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#카메라',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#맛집',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#자연',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#낮',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#캠핑',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#금융',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#책',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#영어',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#DIY',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#남녀차이',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#대학',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#학생',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#고등학교',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#피부',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#메이크업',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#자전거',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#자동차',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#웹툰',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#감성',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#일상',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#셀카',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#포토샵',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#요가',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#가요',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#뷰티',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#정치',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#밤',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#창작',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#댄스',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#해산물',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#키즈',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#부모',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#카페',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#아이폰',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#모바일',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#안드로이드',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#헤어스타일',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#미용',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#음식',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#신발',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#사진',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#술',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#시계',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#가방',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#시',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#미술',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#네일',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#타투',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#인터넷스타',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#축제',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#전시회',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#클럽',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#병원',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#건강',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#디자인',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#과학',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#수학',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#언어',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#이름',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#문화',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#드라마',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#인형',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#과제',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#만화',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#뮤지컬',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#해외',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#국내',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#브랜드',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#명품',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#음료',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#스포츠',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#게임',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#컴퓨터',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#베이커리',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#수업',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#사계절',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#봄',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#여름',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#가을',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#겨울',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#연예인',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#무술',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#악기',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#감정',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#침대',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#인테리어',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#집',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#모델',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#안경',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#가수',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#배우',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#연극',0,0);
Insert into ADMINHASH (HASHNAME,HASHLIKECOUNT,HASHCONTENTCOUNT) values ('#새벽',0,0);
REM INSERTING into ADMINTABLE
SET DEFINE OFF;
REM INSERTING into COMMENTTABLE
SET DEFINE OFF;
Insert into COMMENTTABLE (COMNUM,COMNICK,COMCONTENT,COMCREATEDDATE,COMMODIFIEDDATE,COMREPORTCOUNT,COMBLIND,CONNUM,EMAIL,COMIP) values (55,'jjanggu','asfsadfsdaf',to_date('16/05/12','RR/MM/DD'),to_date('16/05/12','RR/MM/DD'),0,'0',84,'jjanggu1990@naver.com','0:0:0:0:0:0:0:1');
REM INSERTING into CONTENTS
SET DEFINE OFF;
Insert into CONTENTS (CONNUM,CONTENT,CONHASH,CONCREATEDDATE,CONMODIFIEDDATE,CONIP,CONREPORTCOUNT,CONBLIND,EMAIL,CONNICKNAME,CONLIKE) values (82,'박소담 여행','여행',to_date('16/05/04','RR/MM/DD'),to_date('16/05/04','RR/MM/DD'),'192.168.50.3',0,'0','milkis201@naver.com','90',0);
Insert into CONTENTS (CONNUM,CONTENT,CONHASH,CONCREATEDDATE,CONMODIFIEDDATE,CONIP,CONREPORTCOUNT,CONBLIND,EMAIL,CONNICKNAME,CONLIKE) values (84,'잘 나왔냐옹? #냐옹','유머',to_date('16/05/04','RR/MM/DD'),to_date('16/05/04','RR/MM/DD'),'192.168.50.3',0,'0','milkis201@naver.com','90',0);
REM INSERTING into HASHTAG
SET DEFINE OFF;
REM INSERTING into NOTICE
SET DEFINE OFF;
REM INSERTING into PHOTO
SET DEFINE OFF;
Insert into PHOTO (PHOTONUM,PHOTONAME,REALPATH,PHOTOSIZE,CONNUM,EMAIL,SERVERPATH) values (40,'so.png','F:\git_test\INTERHASH\WebContent\upload\so.png','170023',82,'milkis201@naver.com','upload\so.png');
Insert into PHOTO (PHOTONUM,PHOTONAME,REALPATH,PHOTOSIZE,CONNUM,EMAIL,SERVERPATH) values (42,'냐옹.png','F:\git_test\INTERHASH\WebContent\upload\냐옹.png','449042',84,'milkis201@naver.com','upload\냐옹.png');
REM INSERTING into REPORT
SET DEFINE OFF;
REM INSERTING into STATS
SET DEFINE OFF;
REM INSERTING into USERTABLE
SET DEFINE OFF;
Insert into USERTABLE (EMAIL,NICKNAME,PASSWD,HASH,AGE,CREATEDDATE,MODIFIEDDATE,DISTINCTION,REPORTCOUNT) values ('milkis201@naver.com','90','11','[#여행]',90,to_date('16/05/02','RR/MM/DD'),to_date('16/05/02','RR/MM/DD'),0,0);
Insert into USERTABLE (EMAIL,NICKNAME,PASSWD,HASH,AGE,CREATEDDATE,MODIFIEDDATE,DISTINCTION,REPORTCOUNT) values ('jk4877@naver.com','123','123','[#사랑, #커피, #패션, #자연]',24,to_date('16/05/02','RR/MM/DD'),to_date('16/05/02','RR/MM/DD'),0,0);
Insert into USERTABLE (EMAIL,NICKNAME,PASSWD,HASH,AGE,CREATEDDATE,MODIFIEDDATE,DISTINCTION,REPORTCOUNT) values ('the6255@naver.com','sang','1234','[#결혼, #자연, #DIY, #메이크업]',12,to_date('16/05/02','RR/MM/DD'),to_date('16/05/02','RR/MM/DD'),0,0);
Insert into USERTABLE (EMAIL,NICKNAME,PASSWD,HASH,AGE,CREATEDDATE,MODIFIEDDATE,DISTINCTION,REPORTCOUNT) values ('nia1204@naver.com','nia','1234','[#사랑, #커피, #IT]',25,to_date('16/05/03','RR/MM/DD'),to_date('16/05/03','RR/MM/DD'),0,4);
Insert into USERTABLE (EMAIL,NICKNAME,PASSWD,HASH,AGE,CREATEDDATE,MODIFIEDDATE,DISTINCTION,REPORTCOUNT) values ('jk@naver.com','zz','123','null',24,to_date('16/05/04','RR/MM/DD'),to_date('16/05/04','RR/MM/DD'),0,0);
Insert into USERTABLE (EMAIL,NICKNAME,PASSWD,HASH,AGE,CREATEDDATE,MODIFIEDDATE,DISTINCTION,REPORTCOUNT) values ('admin@admin.com','관리자','admin','[#신고]',1,to_date('16/05/03','RR/MM/DD'),to_date('16/05/03','RR/MM/DD'),0,0);
Insert into USERTABLE (EMAIL,NICKNAME,PASSWD,HASH,AGE,CREATEDDATE,MODIFIEDDATE,DISTINCTION,REPORTCOUNT) values ('jjanggu1990@naver.com','jjanggu','1','[#유머, #댄스, #해산물, #키즈, #시계, #시, #네일, #문화, #드라마, #컴퓨터]',27,to_date('16/05/12','RR/MM/DD'),to_date('16/05/12','RR/MM/DD'),0,0);
REM INSERTING into WITHDRAWAL
SET DEFINE OFF;
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (1,'777@com','관리자에 의한 강제탈퇴',to_date('16/05/02','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (2,'jk4879@naver.com','그냥',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (3,'1','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (4,' asdkljflsf','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (5,' 123','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (6,' 123@naver.com','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (7,' gkgkgk','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (8,' 1212','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (9,' test','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (10,' 987','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (11,' 456','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (12,'qq1@naver.com','interhash를 잘 사용하지 못해서',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (13,'asdkljflsf','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (14,'123','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (15,' 123@naver.com','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (16,' gkgkgk','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (17,'456','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (18,'987','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (19,'1212','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (20,'987','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (21,'test','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (22,' admin@admin','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (23,' qq1@naver.com','관리자에 의한 강제탈퇴',to_date('16/05/03','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (24,'jk4879@hanmail.net','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (25,' 123','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (26,'gkgkgk','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (27,'123','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (28,' 123@naver.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (29,'987@naver.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (30,' 1010@naver.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (31,' jk@naver.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (32,' 987','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (33,' admin@admin','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (34,' qq1@naver.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (35,' asdf@asdf.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (36,' 2asdf@asdf.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (37,'987','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (38,'admin@admin','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (39,' qq1@naver.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (40,'1010@naver.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (41,'123@naver.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (42,' jk@naver.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (43,' asdf@asdf.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (44,' 2asdf@asdf.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (45,'2asdf@asdf.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (46,'asdf@asdf.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (47,'jjanggu1990@naver.com','그냥 탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (48,'jjaa@er.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
Insert into WITHDRAWAL (DREWALNUM,DRAWALEMAIL,DRAWALCAUSE,DRAWALDATE) values (49,' milkis201@naver.com','관리자에 의한 강제탈퇴',to_date('16/05/04','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007471
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007471" ON "ADMINHASH" ("HASHNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007439
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007439" ON "ADMINTABLE" ("ADMINNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007450
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007450" ON "COMMENTTABLE" ("COMNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007416
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007416" ON "CONTENTS" ("CONNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007428
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007428" ON "HASHTAG" ("TAGNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007433
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007433" ON "PHOTO" ("PHOTONUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007421
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007421" ON "REPORT" ("RENUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007403
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007403" ON "STATS" ("STATDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007397
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007397" ON "USERTABLE" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007407
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007407" ON "WITHDRAWAL" ("DREWALNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADMINHASH
--------------------------------------------------------

  ALTER TABLE "ADMINHASH" MODIFY ("HASHLIKECOUNT" NOT NULL ENABLE);
  ALTER TABLE "ADMINHASH" MODIFY ("HASHCONTENTCOUNT" NOT NULL ENABLE);
  ALTER TABLE "ADMINHASH" ADD PRIMARY KEY ("HASHNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMINTABLE
--------------------------------------------------------

  ALTER TABLE "ADMINTABLE" ADD PRIMARY KEY ("ADMINNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMENTTABLE
--------------------------------------------------------

  ALTER TABLE "COMMENTTABLE" MODIFY ("COMIP" NOT NULL ENABLE);
  ALTER TABLE "COMMENTTABLE" MODIFY ("COMNICK" NOT NULL ENABLE);
  ALTER TABLE "COMMENTTABLE" MODIFY ("COMCONTENT" NOT NULL ENABLE);
  ALTER TABLE "COMMENTTABLE" MODIFY ("COMCREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "COMMENTTABLE" MODIFY ("COMMODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "COMMENTTABLE" MODIFY ("COMREPORTCOUNT" NOT NULL ENABLE);
  ALTER TABLE "COMMENTTABLE" MODIFY ("COMBLIND" NOT NULL ENABLE);
  ALTER TABLE "COMMENTTABLE" ADD PRIMARY KEY ("COMNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTENTS
--------------------------------------------------------

  ALTER TABLE "CONTENTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CONTENTS" MODIFY ("CONHASH" NOT NULL ENABLE);
  ALTER TABLE "CONTENTS" MODIFY ("CONCREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "CONTENTS" MODIFY ("CONMODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "CONTENTS" MODIFY ("CONIP" NOT NULL ENABLE);
  ALTER TABLE "CONTENTS" MODIFY ("CONREPORTCOUNT" NOT NULL ENABLE);
  ALTER TABLE "CONTENTS" MODIFY ("CONBLIND" NOT NULL ENABLE);
  ALTER TABLE "CONTENTS" ADD PRIMARY KEY ("CONNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HASHTAG
--------------------------------------------------------

  ALTER TABLE "HASHTAG" MODIFY ("TAGALLCOUNT" NOT NULL ENABLE);
  ALTER TABLE "HASHTAG" MODIFY ("TAGCONCOUNT" NOT NULL ENABLE);
  ALTER TABLE "HASHTAG" MODIFY ("TAGINTERCOUNT" NOT NULL ENABLE);
  ALTER TABLE "HASHTAG" MODIFY ("TAGCLASS" NOT NULL ENABLE);
  ALTER TABLE "HASHTAG" ADD PRIMARY KEY ("TAGNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PHOTO
--------------------------------------------------------

  ALTER TABLE "PHOTO" MODIFY ("PHOTONAME" NOT NULL ENABLE);
  ALTER TABLE "PHOTO" MODIFY ("REALPATH" NOT NULL ENABLE);
  ALTER TABLE "PHOTO" MODIFY ("PHOTOSIZE" NOT NULL ENABLE);
  ALTER TABLE "PHOTO" ADD PRIMARY KEY ("PHOTONUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPORT
--------------------------------------------------------

  ALTER TABLE "REPORT" MODIFY ("REDISTINCTION" NOT NULL ENABLE);
  ALTER TABLE "REPORT" ADD PRIMARY KEY ("RENUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATS
--------------------------------------------------------

  ALTER TABLE "STATS" MODIFY ("VISITCOUNT" NOT NULL ENABLE);
  ALTER TABLE "STATS" MODIFY ("CONTENTCOUNT" NOT NULL ENABLE);
  ALTER TABLE "STATS" MODIFY ("COMMENTCOUNT" NOT NULL ENABLE);
  ALTER TABLE "STATS" MODIFY ("REPORTCOUNT" NOT NULL ENABLE);
  ALTER TABLE "STATS" MODIFY ("LIKECOUNT" NOT NULL ENABLE);
  ALTER TABLE "STATS" ADD PRIMARY KEY ("STATDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERTABLE
--------------------------------------------------------

  ALTER TABLE "USERTABLE" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "USERTABLE" MODIFY ("PASSWD" NOT NULL ENABLE);
  ALTER TABLE "USERTABLE" MODIFY ("HASH" NOT NULL ENABLE);
  ALTER TABLE "USERTABLE" MODIFY ("CREATEDDATE" NOT NULL ENABLE);
  ALTER TABLE "USERTABLE" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "USERTABLE" MODIFY ("DISTINCTION" NOT NULL ENABLE);
  ALTER TABLE "USERTABLE" MODIFY ("REPORTCOUNT" NOT NULL ENABLE);
  ALTER TABLE "USERTABLE" ADD PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WITHDRAWAL
--------------------------------------------------------

  ALTER TABLE "WITHDRAWAL" MODIFY ("DRAWALEMAIL" NOT NULL ENABLE);
  ALTER TABLE "WITHDRAWAL" MODIFY ("DRAWALCAUSE" NOT NULL ENABLE);
  ALTER TABLE "WITHDRAWAL" MODIFY ("DRAWALDATE" NOT NULL ENABLE);
  ALTER TABLE "WITHDRAWAL" ADD PRIMARY KEY ("DREWALNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADMINTABLE
--------------------------------------------------------

  ALTER TABLE "ADMINTABLE" ADD CONSTRAINT "SYS_C007286" FOREIGN KEY ("CONNUM")
	  REFERENCES "CONTENTS" ("CONNUM") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ADMINTABLE" ADD CONSTRAINT "SYS_C007287" FOREIGN KEY ("EMAIL")
	  REFERENCES "USERTABLE" ("EMAIL") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ADMINTABLE" ADD CONSTRAINT "SYS_C007288" FOREIGN KEY ("RENUM")
	  REFERENCES "REPORT" ("RENUM") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENTTABLE
--------------------------------------------------------

  ALTER TABLE "COMMENTTABLE" ADD CONSTRAINT "SYS_C007289" FOREIGN KEY ("CONNUM")
	  REFERENCES "CONTENTS" ("CONNUM") ON DELETE CASCADE ENABLE;
  ALTER TABLE "COMMENTTABLE" ADD CONSTRAINT "SYS_C007290" FOREIGN KEY ("EMAIL")
	  REFERENCES "USERTABLE" ("EMAIL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTENTS
--------------------------------------------------------

  ALTER TABLE "CONTENTS" ADD CONSTRAINT "SYS_C007291" FOREIGN KEY ("EMAIL")
	  REFERENCES "USERTABLE" ("EMAIL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HASHTAG
--------------------------------------------------------

  ALTER TABLE "HASHTAG" ADD CONSTRAINT "SYS_C007292" FOREIGN KEY ("EMAIL")
	  REFERENCES "USERTABLE" ("EMAIL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "NOTICE" ADD FOREIGN KEY ("CONNUM")
	  REFERENCES "CONTENTS" ("CONNUM") ENABLE;
  ALTER TABLE "NOTICE" ADD CONSTRAINT "SYS_C007294" FOREIGN KEY ("EMAIL")
	  REFERENCES "USERTABLE" ("EMAIL") ON DELETE CASCADE ENABLE;
  ALTER TABLE "NOTICE" ADD CONSTRAINT "SYS_C007295" FOREIGN KEY ("RENUM")
	  REFERENCES "REPORT" ("RENUM") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHOTO
--------------------------------------------------------

  ALTER TABLE "PHOTO" ADD CONSTRAINT "SYS_C007296" FOREIGN KEY ("CONNUM")
	  REFERENCES "CONTENTS" ("CONNUM") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PHOTO" ADD CONSTRAINT "SYS_C007297" FOREIGN KEY ("EMAIL")
	  REFERENCES "USERTABLE" ("EMAIL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORT
--------------------------------------------------------

  ALTER TABLE "REPORT" ADD CONSTRAINT "SYS_C007298" FOREIGN KEY ("CONNUM")
	  REFERENCES "CONTENTS" ("CONNUM") ON DELETE CASCADE ENABLE;
  ALTER TABLE "REPORT" ADD CONSTRAINT "SYS_C007299" FOREIGN KEY ("EMAIL")
	  REFERENCES "USERTABLE" ("EMAIL") ON DELETE CASCADE ENABLE;
